networks:
  reactionminer:

volumes:
  huggingface:

services:

  # pdf2text + ReactionMiner
  reactionminer:
    image: moleculemaker/reactionminer:execpool
    build:
      context: .
    env_file:
      - .env
    networks:
      - reactionminer

    # Uncomment to utilize NVIDIA GPU
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1 # alternatively, use `count: all` for all GPUs
    #          capabilities: [gpu]

    volumes:
      # Uncomment to map in source code for live dev
      #- .:/workspace

      # HuggingFace API token
      - ./.huggingface/token:/root/.cache/token

      # Input files
      - ./inputs:/workspace/10test/

      # Output files
      - ./results:/workspace/extraction/results_filtered/
    depends_on:
      grobid:
        condition: service_healthy


  # See https://grobid.readthedocs.io/en/latest/Grobid-docker/
  grobid:
    image: grobid/grobid:0.7.3
    networks:
    - reactionminer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
