apiVersion: v1
kind: Pod
metadata:
  name: pdf2text-test
spec:
      containers:
      - name: pdf2text
        image: moleculemaker/reactionminer-pdf2text
        imagePullPolicy: Always
        stdin: true
        tty: true
        command: ["/bin/bash", "-c", "sleep 3600"]
        env:
         - name: GROBID_SERVER
           value: mmli-grobid.staging.svc.cluster.local
        volumeMounts:
        - mountPath: /tmp/results
          name: shared-storage
          subPath: uws/jobs/reactionminer/test3/intermediate
        - mountPath: /tmp/10test
          name: shared-storage
          subPath: uws/jobs/reactionminer/test3/in

      restartPolicy: Never

      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: mmli-clean-job-weights

