apiVersion: batch/v1
kind: Job
metadata:
  name: pdf2text-test
spec:
  template:
    spec:
      containers:
      - name: pdf2text
        image: moleculemaker/reactionminer-pdf2text
        env:
         - name: GROBID_SERVER
           value: mmli-grobid.staging.svc.cluster.local
        volumeMounts:
        - mountPath: /tmp/results
          name: shared-storage
          subPath: uws/jobs/reactionminer/test3/intermediate
        - mountPath: /tmp/10test
          name: shared-storage
          subPath: uws/jobs/reactionminer/test3/in

      restartPolicy: Never

      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: mmli-clean-job-weights

  backoffLimit: 4
