apiVersion: v1
kind: Pod 
metadata:
  name: reactionminer-test
spec:
      #runtimeClassName: nvidia
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.present
                operator: In
                values:
                - 'true'
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        effect: "NoSchedule"
        value: "true"
#      nodeSelector:
#        ncsa.role: worker-gpu
      #securityContext:
      #  fsGroup: 57439
      #  runAsUser: 57439
      #  runAsGroup: 57439
      containers:
      - name: reactionminer
        #image: moleculemaker/reactionminer
        image: moleculemaker/reactionminer-pdf2text
        #image: moleculemaker/reactionminer:micromamba
        #image: moleculemaker/reactionminer:pytorch
        imagePullPolicy: Always
        stdin: true
        tty: true
        command: ["/bin/bash", "-c", "sleep 3600"]
        env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: compute,utility
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
#        resources:
#          requests:
#            memory: "12Gi"
#            cpu: "1"
#          limits:
#            memory: "16Gi"
#            cpu: "2"
        env:
         - name: HF_TOKEN_PATH
           value: /home/mambauser/.huggingface/token
        volumeMounts:
        #- mountPath: /tmp/pdf2text/results
        - mountPath: /workspace/pdf2text/results
          name: shared-storage
          subPath: uws/jobs/reactionminer/test2/out

        - mountPath: /root/.cache/huggingface/hub
          name: shared-storage
          subPath: uws/jobs/reactionminer/.cache

        - mountPath: /home/mambauser/.huggingface/token
          name: token
          readOnly: true
          subPath: token

      restartPolicy: Never

      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: mmli-clean-job-weights

      - name: token
        secret:
          secretName: huggingface-token
          items:
            - key: token
              path: token

